"""dnsmasq PXE/DHCP 配置生成与控制"""
import json
import os
import subprocess

from app.config import settings
from app.exceptions import PxeException
from app.utils.systemd import is_active


def generate_config(interface: str, dhcp_range: str, tftp_server: str = "", mac_filters: dict = None) -> str:
    """生成 dnsmasq 配置内容

    Args:
        interface: 监听网卡
        dhcp_range: DHCP 地址池 (如 192.168.1.100,192.168.1.200,12h)
        tftp_server: TFTP 根目录
        mac_filters: MAC 地址到引导文件的映射 {mac: filename}

    Returns:
        dnsmasq.conf 内容
    """
    lines = [
        "# Auto-generated by PXE Manager",
        f"interface={interface}",
        "bind-interfaces",
        f"dhcp-range={dhcp_range},static,12h",
        "dhcp-option=option:router,192.168.1.1",
        "",
        "# PXE Boot",
        "dhcp-boot=undionly.kpxe",
        "",
    ]
    if tftp_server:
        lines.append(f"enable-tftp")
        lines.append(f"tftp-root={tftp_server}")
    else:
        lines.append("enable-tftp")
        lines.append(f"tftp-root={settings.tftp_root}")
    lines.append("")

    if mac_filters:
        lines.append("# MAC-specific boot files")
        for mac, filename in mac_filters.items():
            lines.append(f"dhcp-host={mac},{filename}")
        lines.append("")

    return "\n".join(lines)


def apply_config(content: str) -> None:
    """写入 /etc/dnsmasq.conf 并重启服务"""
    conf_path = "/etc/dnsmasq.conf"
    if not os.path.exists(conf_path) and os.geteuid() != 0:
        raise PxeException("PERMISSION_DENIED", "需要 root 权限写入配置文件")
    try:
        with open(conf_path, "w") as f:
            f.write(content)
        subprocess.run(
            ["systemctl", "restart", "dnsmasq"],
            check=True,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except subprocess.CalledProcessError as e:
        raise PxeException("APPLY_CONFIG_ERROR", f"重启 dnsmasq 失败: {e.stderr.strip()}")


def get_config() -> str:
    """读取当前 dnsmasq 配置"""
    conf_path = "/etc/dnsmasq.conf"
    try:
        with open(conf_path, "r") as f:
            return f.read()
    except FileNotFoundError:
        return ""


def add_mac_filter(mac: str, filename: str) -> dict:
    """添加 MAC 地址到引导文件映射

    Returns:
        更新后的 mac_filters 字典
    """
    filters = get_mac_filters()
    filters[mac] = filename
    save_mac_filters(filters)
    return filters


def remove_mac_filter(mac: str) -> dict:
    """移除 MAC 过滤规则

    Returns:
        更新后的 mac_filters 字典
    """
    filters = get_mac_filters()
    filters.pop(mac, None)
    save_mac_filters(filters)
    return filters


def get_mac_filters() -> dict:
    """从当前配置读取 MAC 过滤器"""
    filters = {}
    config = get_config()
    for line in config.splitlines():
        if line.startswith("dhcp-host="):
            parts = line.split(",")
            if len(parts) >= 2:
                filters[parts[0].replace("dhcp-host=", "")] = parts[1]
    return filters


def save_mac_filters(filters: dict) -> None:
    """保存 MAC 过滤器到配置"""
    config = get_config()
    lines = config.splitlines()
    new_lines = []
    filter_line = False
    for line in lines:
        if line == "# MAC-specific boot files":
            filter_line = True
            new_lines.append(line)
            continue
        if filter_line:
            if line.startswith("dhcp-host="):
                continue
            filter_line = False
        new_lines.append(line)

    if filters:
        new_lines.append("# MAC-specific boot files")
        for mac, filename in filters.items():
            new_lines.append(f"dhcp-host={mac},{filename}")

    config = "\n".join(new_lines)
    apply_config(config)


def get_service_status() -> dict:
    """获取 dnsmasq 服务状态"""
    return {
        "running": is_active("dnsmasq"),
        "config": get_config(),
    }
