"""iPXE 引导菜单生成"""
import os

from app.config import settings
from app.exceptions import PxeException


def generate_menu(isos: list = None, hosts: list = None, mac_menus: dict = None) -> str:
    """根据 ISO 镜像和主机列表生成 iPXE 菜单

    Args:
        isos: ISO 镜像列表 [{name, local_path, arch}]
        hosts: 主机列表 [{hostname, mac_address}]
        mac_menus: MAC 定制菜单 {mac: {name, kernel, initrd}}

    Returns:
        iPXE 脚本内容
    """
    lines = [
        "#!ipxe",
        "# Auto-generated by PXE Manager",
        ":menu",
        "set menu-timeout 60000",
        "set menu-default install-ubuntu",
        "",
        'choose --default install-ubuntu --timeout 60000 target && goto ${target}',
        '',
        'item --gap --------- Menu ---------',
        "item install-ubuntu Install Ubuntu 22.04 Server",
    ]

    if isos:
        for iso in isos:
            label = f"install-{iso.get('name', 'custom').lower().replace(' ', '-')}"
            lines.append(f"item {label} Install {iso.get('name', 'Custom')}")

    if hosts:
        lines.append("")
        lines.append("item --gap --------- Host-Specific ---------")
        for host in hosts:
            label = f"boot-{host['hostname'].replace('.', '-').replace('_', '-')}"
            lines.append(f"item {label} Boot {host['hostname']}")

    lines.append("item shell iPXE Shell")
    lines.append("")

    # Ubuntu 22.04 default label
    lines.append(":install-ubuntu")
    lines.append("set kernel_path images/ubuntu2204/vmlinuz")
    lines.append("set initrd_path images/ubuntu2204/initrd")
    lines.append("set ds_path ipxe/user-data")
    lines.append("kernel ${kernel_path} ip=dhcp auto=true net.ifnames=0")
    lines.append("initrd ${initrd_path}")
    lines.append('boot || goto menu')
    lines.append("")

    # Custom ISO labels
    if isos:
        for iso in isos:
            label = f"install-{iso.get('name', 'custom').lower().replace(' ', '-')}"
            kernel = iso.get("kernel_path", f"images/{iso['name']}/vmlinuz")
            initrd = iso.get("initrd_path", f"images/{iso['name']}/initrd")
            lines.append(f":{label}")
            lines.append(f"kernel {kernel} ip=dhcp")
            lines.append(f"initrd {initrd}")
            lines.append("boot || goto menu")
            lines.append("")

    # Host-specific labels
    if hosts:
        for host in hosts:
            label = f"boot-{host['hostname'].replace('.', '-').replace('_', '-')}"
            lines.append(f":{label}")
            lines.append(f"set mac {host.get('mac_address', '')}")
            lines.append("kernel images/ubuntu2204/vmlinuz ip=dhcp")
            lines.append("initrd images/ubuntu2204/initrd")
            lines.append("boot || goto menu")
            lines.append("")

    # MAC-specific menus
    if mac_menus:
        for mac, menu in mac_menus.items():
            label = f"mac-{mac.replace(':', '')}"
            lines.append(f":{label}")
            lines.append(f"kernel {menu.get('kernel', 'vmlinuz')}")
            lines.append(f"initrd {menu.get('initrd', 'initrd')}")
            lines.append("boot || goto menu")
            lines.append("")

    # Shell label
    lines.append(":shell")
    lines.append("shell")
    lines.append("")
    lines.append("goto menu")

    return "\n".join(lines)


def write_menu(content: str, filename: str = "default.ipxe") -> str:
    """写入 iPXE 引导文件

    Args:
        content: iPXE 脚本内容
        filename: 引导文件名

    Returns:
        文件完整路径
    """
    ipxe_dir = os.path.join(settings.tftp_root, "ipxe")
    os.makedirs(ipxe_dir, exist_ok=True)
    filepath = os.path.join(ipxe_dir, filename)
    with open(filepath, "w") as f:
        f.write(content)
    return filepath
